spring:
  redis:
    port: 6379
    host: localhost
  data:
    mongodb:
      host: localhost
      port: 27017
      database: iotgenedu
  #      uri: mongodb://localhost:27017/iotgenedu
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
    queueName: giovanny
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: gioavnny
      auto-offset-reset: latest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 200
    producer:
      linger-ms: 200
      batch-size: 16384
      compression-type: gzip
      retries: 3
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    name: production
    url: jdbc:mysql://127.0.0.1:3306/wxeducation?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#线程池配置
executor:
  corePoolSize: 20
  maxPoolSize: 30
  queueCapacity: 45
